title: Brf Stenklevsgatan 1
description: >- 
  Hemsida för bostadsrättföreningen Stenklevsgatan 1 i Majorna
include: ["_pages", "_data"]
locale: "sv-SE"

# Build settings
remote_theme: "mmistakes/minimal-mistakes@4.20.1"
plugins:
  - jekyll-feed
  - jekyll-include-cache

defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single