title: BRF Stenklevsgatan 1
description: >- 
  Hemsida för bostadsrättföreningen Stenklevsgatan 1 i Majorna
include: ["_pages", "_data"]
locale: "sv-SE"

remote_theme: "mmistakes/minimal-mistakes@4.24.0"

plugins:
  - jekyll-feed
  - jekyll-include-cache

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single